name: Build and pack nuget
on:
  push:
    branches:
      - main
      - dev-ci-cd-github
    tags:
      - '*' # 触发所有tag

env:
  IS_PRODUCTION: true
  TAG: ${{ github.ref_name }} # 获取当前分支名或tag名
  NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  prod-check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x    
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-build-nuget-${{ env.CACHE_NAME }}-       
     
      - name: set production variable
        if: ${{ github.ref_type == 'branch' }}
        env:
          IS_PRODUCTION: false
        run: |
          Write-Host ${{env.IS_PRODUCTION}}
          Write-Host ${{env.TAG}}


  build:
    runs-on: windows-latest
    needs: prod-check    
    steps:
      - name: Restore dependencies
        run: dotnet restore
      - name: Build with dotnet
        run: dotnet build --configuration Release    
      - name: Pack with powershell
        shell: pwsh
        working-directory: ./nupkg
        run: ./pack.ps1

  deploy-push-nuget:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Push NuGet package
        working-directory: ./nupkg/dist
        run: ./pack_push.ps1
        shell: pwsh


  deploy-push-github-pkg:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Publish to GitHub Nuget Packages      
        run: dotnet nuget push nupkg/*.nupkg --source "github"
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
